INSERT INTO APARTMENT_BLOCK VALUES(1,'BLOCK-1','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(2,'BLOCK-2','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(3,'BLOCK-3','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(4,'BLOCK-4','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(5,'BLOCK-5','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(6,'BLOCK-6','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(7,'BLOCK-7','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(8,'BLOCK-8','NOUAKCHOT');
INSERT INTO APARTMENT_BLOCK VALUES(9,'BLOCK-9','NOUAKCHOT');

